### PR TITLE
add basic doc structure

### PR DESCRIPTION
**Pull request by mrocklin**
I used sphinx-quickstart but added some extensions and changed the style to default.  I've added a simple description of the project as well as a skeleton for API docs.  Hopefully having this up will encourage people to write docstrings and docs.

### CODE REVIEW

**Comment by mrocklin** [comment]
We have a slight problem with readthedocs.  To build API docs the project needs to be importable; the libhdfs3.so makes this a bit tricky.  One of the following solutions would work:

1.  Readthedocs now supports conda builds, so a conda package would be dandy.  This is probably the right solution going forward but will take some time.
2.  We could guard all use of `_lib` within the main library.  This looks a bit ugly but can happen immediately.

**Comment by martindurant** [comment]
You mean simply try/except the import, or make a little class 
```python
class _lib():
    def __getattr__(self, *args):
        raise RuntimeError("Library not imported")
```

**Comment by mrocklin** [comment]
When doing this locally I added try-except around the creation of lib

```python
try:
    _lib = ...
except OSError:
    _lib = False
```

And then I guarded the use of _lib later on in the libary

```python
if _lib:
    set output types to various functions
```

**Comment by mrocklin** [comment]
Merging on passing tests

**Pull request merged**
